@extends('admin.layouts.app')
@section('heading', $account->account_number)
@section('page_description', 'Installment account, schedule, payments, notes, and full financial history.')
@section('content')
<div class="admin-grid admin-grid-3">
    <section class="admin-card"><h3 class="admin-card__title">Customer</h3><p><strong>{{ $account->user->name }}</strong><br>{{ $account->application->email }}<br>{{ $account->application->phone }}<br>{{ $account->application->address }}</p></section>
    <section class="admin-card"><h3 class="admin-card__title">Product snapshot</h3><p><strong>{{ $account->application->product_name_snapshot }}</strong><br>SKU {{ $account->application->product_sku_snapshot ?: '—' }}<br>{{ $account->application->storage_snapshot }} {{ $account->application->color_snapshot }}<br>Price {{ number_format($account->original_principal_cents/100,2) }} {{ $account->currency }}</p></section>
    <section class="admin-card"><h3 class="admin-card__title">Account</h3><p>Status: <strong>{{ $account->account_status }}</strong><br>Total: {{ number_format($account->total_payable_cents/100,2) }}<br>Paid: {{ number_format($account->amount_paid_cents/100,2) }}<br>Remaining: {{ number_format($account->remaining_balance_cents/100,2) }}<br>Overdue: {{ number_format($account->overdue_amount_cents/100,2) }}</p></section>
</div>

<section class="admin-card" style="margin-top:20px"><div class="admin-card__header"><div><h3 class="admin-card__title">Schedule</h3><p class="admin-card__copy">Effective statuses include the current date and live allocation totals.</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>#</th><th>Due date</th><th>Amount</th><th>Paid</th><th>Remaining</th><th>Status</th></tr></thead><tbody>@foreach($account->scheduleItems as $item)<tr><td>{{ $item->installment_number }}</td><td>{{ $item->due_date->format('M j, Y') }}</td><td>{{ number_format($item->amount_due_cents/100,2) }}</td><td>{{ number_format($item->amount_paid_cents/100,2) }}</td><td>{{ number_format($item->remaining_cents/100,2) }}</td><td><span class="admin-status-badge admin-status-badge--{{ $item->effective_status==='overdue'?'danger':($item->effective_status==='paid'?'success':'neutral') }}">{{ $item->effective_status }}</span></td></tr>@endforeach</tbody></table></div></section>

@if($account->account_status === 'active')
<div class="admin-grid admin-grid-2" style="margin-top:20px"><section class="admin-card"><h3 class="admin-card__title">Record payment</h3><form method="POST" action="{{ route('admin.installments.payments.store',$account) }}" class="admin-form-grid">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><label class="admin-field"><span class="admin-label">Amount ({{ $account->currency }})</span><input class="admin-input" name="amount" inputmode="decimal" required></label><label class="admin-field"><span class="admin-label">Method</span><select class="admin-select" name="payment_method">@foreach(\App\Models\InstallmentPayment::METHODS as $method)<option value="{{ $method }}">{{ str($method)->replace('_',' ')->headline() }}</option>@endforeach</select></label><label class="admin-field"><span class="admin-label">Paid at</span><input class="admin-input" type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><input class="admin-input" name="reference" placeholder="Reference (optional)"><textarea class="admin-textarea" name="notes" placeholder="Payment notes (optional)"></textarea><button class="admin-button">Record payment</button></form></section><section class="admin-card"><h3 class="admin-card__title">Cancel account</h3><p class="admin-card__copy">Cancellation stops future payments but retains the schedule, payments, application, and audit history.</p><form method="POST" action="{{ route('admin.installments.cancel',$account) }}" class="admin-form-grid">@csrf<textarea class="admin-textarea" name="reason" required placeholder="Cancellation reason"></textarea><button class="admin-button admin-button--danger">Cancel account</button></form></section></div>
@endif

<section class="admin-card" style="margin-top:20px"><h3 class="admin-card__title">Payments</h3><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Date</th><th>Receipt</th><th>Amount</th><th>Method</th><th>Reference</th><th>Recorded by</th><th>Actions</th></tr></thead><tbody>@forelse($account->payments as $payment)<tr style="{{ $payment->is_reversed?'opacity:.55':'' }}"><td>{{ $payment->paid_at->format('M j, Y H:i') }}</td><td>{{ $payment->receipt_number }} @if($payment->is_reversed)<strong>(REVERSED)</strong>@endif</td><td>{{ number_format($payment->amount_cents/100,2) }}</td><td>{{ str($payment->payment_method)->replace('_',' ')->headline() }}</td><td>{{ $payment->reference ?: '—' }}</td><td>{{ $payment->recorder->name }}</td><td><a class="admin-link-button" href="{{ route('admin.installments.payments.receipt',[$account,$payment]) }}">Receipt</a>@if(!$payment->is_reversed && $account->account_status!=='cancelled')<form method="POST" action="{{ route('admin.installments.payments.reverse',[$account,$payment]) }}" style="margin-top:8px">@csrf<input class="admin-input" name="reversal_reason" required placeholder="Reversal reason"><button class="admin-button admin-button--danger" style="margin-top:6px">Reverse</button></form>@endif</td></tr>@empty<tr><td colspan="7">No payments recorded.</td></tr>@endforelse</tbody></table></div></section>

<div class="admin-grid admin-grid-2" style="margin-top:20px"><section class="admin-card"><h3 class="admin-card__title">Internal notes</h3><form method="POST" action="{{ route('admin.installments.notes.store',$account) }}" class="admin-form-grid">@csrf<textarea class="admin-textarea" name="note" required placeholder="Visible to administrators only"></textarea><button class="admin-button">Add note</button></form>@foreach($account->notes as $note)<div class="admin-row-card" style="margin-top:12px"><p>{{ $note->note }}</p><small>{{ $note->author->name }} · {{ $note->created_at }}</small></div>@endforeach</section><section class="admin-card"><h3 class="admin-card__title">Audit history</h3>@foreach($account->events as $event)<div class="admin-row-card" style="margin-top:12px"><strong>{{ str($event->event_type)->replace('_',' ')->headline() }}</strong><p>{{ $event->description }}</p><small>{{ $event->performer?->name }} · {{ $event->created_at }}</small></div>@endforeach</section></div>

<section class="admin-card" style="margin-top:20px"><h3 class="admin-card__title">Application & private documents</h3><p><a class="admin-link-button" href="{{ route('admin.installment-applications.show',$account->application) }}">View {{ $account->application->application_number }}</a></p>@foreach($account->application->documents as $document)<a class="admin-link-button" href="{{ route('admin.installment-applications.documents.show',[$account->application,$document]) }}">{{ str($document->type)->replace('_',' ')->headline() }}</a>@endforeach</section>
@endsection
