@php($checklist = old('condition_checklist', $deviceUnit->condition_checklist ?? []))
@php($included = old('included_accessories', $deviceUnit->included_accessories ?? []))
<x-admin.validation-errors />
<div class="admin-grid">
<section class="admin-card"><div class="admin-card__header"><div><h3 class="admin-card__title">1. Catalog identity</h3><p class="admin-card__copy">Choose the existing model, storage and color variant.</p></div></div>
<div class="admin-form-grid admin-form-grid-2">
<label class="admin-field"><span class="admin-label">Product variant</span><select required name="product_variant_id" class="admin-select"><option value="">Select a variant</option>@foreach($variants as $variant)<option value="{{ $variant->id }}" @selected((int)old('product_variant_id', $deviceUnit->product_variant_id) === $variant->id)>{{ trim($variant->product->brand.' '.$variant->product->name) }} — {{ $variant->sku }} @if($variant->optionValues->isNotEmpty())({{ $variant->optionValues->pluck('display_name')->filter()->join(', ') }})@endif</option>@endforeach</select></label>
<label class="admin-field"><span class="admin-label">IMEI</span><input required name="imei" class="admin-input" inputmode="numeric" maxlength="18" value="{{ old('imei', $deviceUnit->exists ? $deviceUnit->imei : '') }}"><span class="admin-help">Encrypted at rest; a normalized SHA-256 hash enforces uniqueness and exact search.</span></label>
<label class="admin-field"><span class="admin-label">Serial number</span><input name="serial_number" class="admin-input" value="{{ old('serial_number', $deviceUnit->exists ? $deviceUnit->serial_number : '') }}"></label>
<label class="admin-field"><span class="admin-label">Status</span><select name="status" class="admin-select">@foreach($statuses as $option)<option value="{{ $option->value }}" @selected(old('status', $deviceUnit->status?->value ?? 'repair') === $option->value)>{{ $option->label() }}</option>@endforeach</select><span class="admin-help">Returned devices stay hidden until inspected and manually marked available.</span></label>
</div></section>
<section class="admin-card"><div class="admin-card__header"><div><h3 class="admin-card__title">2. Condition & pricing</h3><p class="admin-card__copy">Customer-visible facts must be candid and specific.</p></div></div><div class="admin-form-grid admin-form-grid-2">
<label class="admin-field"><span class="admin-label">Condition</span><select name="condition_type" class="admin-select">@foreach($conditions as $option)<option value="{{ $option->value }}" @selected(old('condition_type', $deviceUnit->condition_type?->value) === $option->value)>{{ $option->label() }}</option>@endforeach</select></label>
<label class="admin-field"><span class="admin-label">Grade</span><select name="condition_grade" class="admin-select">@foreach($grades as $option)<option value="{{ $option->value }}" @selected(old('condition_grade', $deviceUnit->condition_grade?->value) === $option->value)>{{ $option->label() }}</option>@endforeach</select></label>
<label class="admin-field"><span class="admin-label">Battery health %</span><input type="number" min="0" max="100" name="battery_health_percent" class="admin-input" value="{{ old('battery_health_percent', $deviceUnit->battery_health_percent) }}"></label>
<label class="admin-field"><span class="admin-label">Selling price override</span><input inputmode="decimal" name="selling_price_override" class="admin-input" value="{{ old('selling_price_override', $deviceUnit->selling_price_override_cents === null ? '' : number_format($deviceUnit->selling_price_override_cents / 100, 2, '.', '')) }}"><span class="admin-help">Leave blank to inherit the variant price.</span></label>
<label class="admin-field"><span class="admin-label">Acquisition cost</span><input inputmode="decimal" name="acquisition_cost" class="admin-input" value="{{ old('acquisition_cost', $deviceUnit->acquisition_cost_cents === null ? '' : number_format($deviceUnit->acquisition_cost_cents / 100, 2, '.', '')) }}"><span class="admin-help">Private; used only for profit snapshots.</span></label>
<label class="admin-field"><span class="admin-label">Warranty days</span><input type="number" min="0" name="warranty_days" class="admin-input" value="{{ old('warranty_days', $deviceUnit->warranty_days) }}"></label>
<label class="admin-field"><span class="admin-label">Explicit warranty end</span><input type="date" name="warranty_until" class="admin-input" value="{{ old('warranty_until', $deviceUnit->warranty_until?->toDateString()) }}"></label>
<label class="admin-field"><span class="admin-label">Cosmetic summary</span><textarea name="cosmetic_condition" class="admin-textarea">{{ old('cosmetic_condition', $deviceUnit->cosmetic_condition) }}</textarea></label>
<label class="admin-field"><span class="admin-label">Customer-visible condition notes</span><textarea name="customer_visible_condition_notes" class="admin-textarea">{{ old('customer_visible_condition_notes', $deviceUnit->customer_visible_condition_notes) }}</textarea></label>
<label class="admin-field"><span class="admin-label">Known defects (one per line)</span><textarea name="known_defects" class="admin-textarea">{{ old('known_defects', implode("\n", $deviceUnit->known_defects ?? [])) }}</textarea></label>
<label class="admin-field"><span class="admin-label">Installments</span><span><input type="checkbox" name="installments_enabled" value="1" @checked(old('installments_enabled', $deviceUnit->installments_enabled))> Allow configured variant installment plans</span></label>
</div></section>
<section class="admin-card"><div class="admin-card__header"><div><h3 class="admin-card__title">3. Functional checklist</h3><p class="admin-card__copy">Use controlled states so faults can be filtered and displayed consistently.</p></div></div><div class="admin-form-grid admin-form-grid-3">@foreach($checklistKeys as $key)<label class="admin-field"><span class="admin-label">{{ str($key)->replace('_', ' ')->headline() }}</span><select name="condition_checklist[{{ $key }}]" class="admin-select"><option value="">Not recorded</option>@foreach($checkStatuses as $option)<option value="{{ $option->value }}" @selected(data_get($checklist, $key) === $option->value)>{{ $option->label() }}</option>@endforeach</select></label>@endforeach</div></section>
<section class="admin-card"><div class="admin-card__header"><div><h3 class="admin-card__title">4. Accessories & refurbishment</h3></div></div><div class="admin-form-grid admin-form-grid-2">
<div class="admin-field"><span class="admin-label">Included items</span><div class="admin-inline">@foreach($accessoryKeys as $key)<label><input type="checkbox" name="included_accessories[]" value="{{ $key }}" @checked(in_array($key, $included, true))> {{ str($key)->replace('_', ' ')->headline() }}</label>@endforeach</div></div>
<label class="admin-field"><span class="admin-label">Refurbished date</span><input type="date" name="refurbished_at" class="admin-input" value="{{ old('refurbished_at', $deviceUnit->refurbished_at?->toDateString()) }}"></label>
<label class="admin-field"><span class="admin-label">Refurbished by</span><input name="refurbished_by" class="admin-input" value="{{ old('refurbished_by', $deviceUnit->refurbished_by) }}"></label>
<label class="admin-field"><span class="admin-label">Parts replaced (one per line)</span><textarea name="parts_replaced" class="admin-textarea">{{ old('parts_replaced', implode("\n", $deviceUnit->parts_replaced ?? [])) }}</textarea></label>
<label class="admin-field"><span class="admin-label">Customer-visible refurbishment details</span><textarea name="customer_visible_refurbishment_details" class="admin-textarea">{{ old('customer_visible_refurbishment_details', $deviceUnit->customer_visible_refurbishment_details) }}</textarea></label>
<label class="admin-field"><span class="admin-label">Private technician notes</span><textarea name="refurbishment_notes" class="admin-textarea">{{ old('refurbishment_notes', $deviceUnit->refurbishment_notes) }}</textarea></label>
</div></section>
<section class="admin-card"><div class="admin-card__header"><div><h3 class="admin-card__title">5. Exact-device photos</h3><p class="admin-card__copy">Upload real photos; these take priority over variant and product galleries.</p></div></div>
@if($deviceUnit->exists && $deviceUnit->images->isNotEmpty())<div class="admin-grid admin-grid-4">@foreach($deviceUnit->images as $image)<label class="admin-row-card"><img src="{{ asset('storage/'.$image->image_path) }}" alt="{{ $image->alt_text }}" style="width:100%;height:150px;object-fit:contain"><span><input type="checkbox" name="remove_image_ids[]" value="{{ $image->id }}"> Remove</span></label>@endforeach</div>@endif
<label class="admin-field"><span class="admin-label">Photos</span><input type="file" multiple accept="image/*" name="images[]" class="admin-file-input"></label>
</section>
<div class="admin-actions"><button class="admin-button" type="submit">Save device unit</button><a class="admin-link" href="{{ route('admin.device-units.index') }}">Cancel</a></div>
</div>
