@extends('layouts.elite-mobile-marketplace')
@section('title','Installment Service | خدمة التقسيط')
@section('content')
<x-public.public-header />
<x-public.category-drawer :categories="$menuCategories" />
<x-public.search-overlay />
<main class="pm-finance-page" dir="auto">
 <section class="pm-finance-hero">
    <div class="pm-finance-hero__copy"><p class="pm-luxury-kicker">Installment Service · خدمة التقسيط</p><h1>Your next device,<br><em>within reach.</em></h1><p>Choose exceptional technology today and pay with a considered schedule designed around you. Apply online in a few guided steps.</p><div class="flex flex-wrap gap-3"><a class="pm-button pm-button--luxury" href="{{ route('installments.create') }}">Begin your application <span class="material-symbols-outlined">arrow_forward</span></a><a class="pm-button pm-button--luxury-outline" href="{{ route('catalog.index') }}">Explore devices</a></div><small>Approval is subject to review · الموافقة خاضعة للمراجعة</small></div>
    <div class="pm-finance-hero__visual" aria-hidden="true"><div class="pm-finance-card"><span>TAQQSIT</span><strong>Flexible<br>by design.</strong><small>03 · 06 · 09</small></div><div class="pm-finance-device"></div><div class="pm-finance-ring"></div></div>
 </section>
 <section class="pm-finance-trust" aria-label="Service highlights"><div><strong>03</strong><span>Simple stages</span></div><div><strong>100%</strong><span>Online application</span></div><div><strong>Clear</strong><span>Payment schedule</span></div><div><strong>Human</strong><span>Review & support</span></div></section>
 <section class="pm-finance-process" aria-labelledby="finance-process-title"><div class="pm-editorial-heading"><p>A guided experience</p><h2 id="finance-process-title">From selection to collection.</h2></div><div class="pm-finance-process__steps"><article><span>01</span><i class="material-symbols-outlined">devices</i><h3>Choose your device</h3><p>Select the model, configuration, and payment duration that suit you.</p><small lang="ar" dir="rtl">اختر جهازك</small></article><article><span>02</span><i class="material-symbols-outlined">assignment_turned_in</i><h3>Apply for review</h3><p>Share your details and documents through our secure guided form.</p><small lang="ar" dir="rtl">قدّم طلبك للمراجعة</small></article><article><span>03</span><i class="material-symbols-outlined">shopping_bag</i><h3>Collect with confidence</h3><p>Once approved, sign the agreement and make your first payment.</p><small lang="ar" dir="rtl">استلم جهازك</small></article></div></section>
 <section class="pm-document-suite"><div><p class="pm-luxury-kicker">Prepared in advance</p><h2>Everything you need,<br>nothing you don’t.</h2><p>Keep these documents ready for a smooth, secure application.</p><a href="{{ route('installments.create') }}" class="pm-editorial-link">Start now <span class="material-symbols-outlined">arrow_forward</span></a></div><ul><li><span class="material-symbols-outlined">badge</span><p><strong>Proof of identity</strong><small>Lebanese ID, passport, or Civil Registry Extract</small></p></li><li><span class="material-symbols-outlined">home_pin</span><p><strong>Proof of address</strong><small>Residence certificate, electricity bill, or water bill</small></p></li><li><span class="material-symbols-outlined">family_restroom</span><p><strong>Name verification</strong><small>The address document may be in your name or a parent’s</small></p></li><li><span class="material-symbols-outlined">account_balance_wallet</span><p><strong>Simple repayments</strong><small>Approved remaining installments are paid through Whish Money</small></p></li></ul></section>
 <section class="pm-finance-cta"><p>Ready when you are.</p><h2>Make your next device possible.</h2><a class="pm-button pm-button--luxury" href="{{ route('installments.create') }}">Apply now / قدّم الآن <span class="material-symbols-outlined">arrow_forward</span></a></section>
</main>
<x-public.support-button />
@include('elite-mobile-marketplace.partials.bottom-nav')
@endsection
