<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Receipt {{ $sale->reference }}</title><style>body{margin:0;background:#eef2f6;color:#111827;font:14px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}.receipt{width:min(100% - 24px,420px);margin:24px auto;background:#fff;padding:28px;box-shadow:0 12px 35px rgba(15,23,42,.14)}h1{font-size:21px;margin:0}.center{text-align:center}.muted{color:#64748b}.rule{border:0;border-top:1px dashed #94a3b8;margin:18px 0}.row{display:flex;justify-content:space-between;gap:18px}.item{margin:13px 0}.item-name{font-weight:700}.total{font-size:19px;font-weight:800}.actions{text-align:center;margin:18px}.actions button{border:0;border-radius:10px;background:#1d4ed8;color:#fff;padding:12px 18px;font-weight:700;cursor:pointer}.status{font-weight:800;text-transform:uppercase}@media print{body{background:#fff}.receipt{width:auto;margin:0;box-shadow:none;padding:0}.actions{display:none}@page{margin:10mm}}</style></head>
<body><div class="actions"><button onclick="window.print()">Print receipt</button></div><main class="receipt">
    <header class="center"><h1>{{ config('app.name') }}</h1><div>Point of Sale Receipt</div>@if($sale->status==='refunded')<div class="status">REFUNDED</div>@endif</header><hr class="rule">
    <div>Receipt: <strong>{{ $sale->reference }}</strong></div><div>Date: {{ $sale->created_at->format('Y-m-d H:i:s') }}</div><div>Cashier: {{ $sale->cashier_name ?: $sale->cashier?->name ?: 'Former user' }}</div><hr class="rule">
    @foreach($sale->items as $item)<section class="item"><div class="item-name">{{ $item->product_name }}</div><div class="muted">{{ collect($item->variant_options)->values()->join(' / ') }} · {{ $item->sku }}</div><div class="row"><span>{{ $item->quantity }} × ${{ number_format($item->unit_price_cents/100,2) }}</span><strong>${{ number_format($item->total_cents/100,2) }}</strong></div></section>@endforeach
    <hr class="rule"><div class="row"><span>Subtotal</span><span>${{ number_format($sale->subtotal_cents/100,2) }}</span></div>@if($sale->discount_cents)<div class="row"><span>Discount @if($sale->discount_type==='percentage')({{ rtrim(rtrim($sale->discount_value,'0'),'.') }}%)@endif</span><span>−${{ number_format($sale->discount_cents/100,2) }}</span></div>@endif<div class="row total"><span>Total</span><span>${{ number_format($sale->total_cents/100,2) }}</span></div><hr class="rule">
    @foreach($sale->payments as $payment)<div class="row"><span>{{ str($payment->payment_method)->headline() }}@if($payment->reference) ({{ $payment->reference }})@endif</span><span>${{ number_format($payment->amount_cents/100,2) }}</span></div>@if($payment->payment_method==='cash' && $payment->cash_received_cents!==null)<div class="row muted"><span>Cash received</span><span>${{ number_format($payment->cash_received_cents/100,2) }}</span></div><div class="row muted"><span>Change</span><span>${{ number_format($payment->change_due_cents/100,2) }}</span></div>@endif @endforeach
    @if($sale->discount_cents)<hr class="rule"><div class="muted">Sale discount: ${{ number_format($sale->discount_cents/100,2) }}</div>@endif
    <hr class="rule"><div class="center muted">Thank you</div>
</main></body></html>
